name: klasik
version: '1.0-SNAPSHOT'
main: klasik.klasik.Klasik
api-version: '1.20'
commands:
  fly:
    description: a
    usage: /fly
    aliases: f
    permission: fly
    permission-message: Brak dostępu do komendy!
  back:
    description: b
    usage: /back
    aliases: b
  home:
    description: c
    usage: /home
    aliases: /h